%{
For FBHALE software
Copyright (C) 2018-present Facebook, Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
%}
  
function [ optim ] = WriteBoom(  optim, aswingIn, useStructure, relfectionY_m, beamNumber, entityName, index  )
% Write beams into .asw file

fprintf(aswingIn,'\n');

fprintf(aswingIn,'#============\n');
fprintf(aswingIn,['Beam ' num2str(beamNumber) '\n']);
fprintf(aswingIn,[entityName '\n']);
fprintf(aswingIn,'#\n');

fprintf(aswingIn,'\n');
fprintf(aswingIn,'    t       x     y   radius     mg  Cea  Nea  Cta  Nta  mgcc  Ccg  Ncg\n');

%boom geometric properties
for i=1:length(optim.boom.omlSectionsX_m{index})

    fprintf(aswingIn,'\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\n', ...
    optim.boom.omlSectionsX_m{index}(i)/ optim.boom.omlSectionsX_m{index}(end), ...
    optim.boom.globalx_m{index}(i), ...
    relfectionY_m*optim.boom.globaly_m{index}(i), ...
    optim.boom.omlSectionsR_m{index}(i), ...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.mg_N_m{index},     optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Cea_m{index},   optim.boom.omlSectionsX_m{index}(i),'linear','extrap'),  ...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Nea_m{index},   optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Cta_m{index},   optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Nta_m{index},   optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.mgcc_Nm{index}, optim.boom.omlSectionsX_m{index}(i),'linear','extrap'),...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Ccg_m{index},   optim.boom.omlSectionsX_m{index}(i),'linear','extrap'),  ...
    interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Ncg_m{index},   optim.boom.omlSectionsX_m{index}(i),'linear','extrap'));
end

% boom structural properties
if useStructure(4) == 0
    %don't print structural properties 
else 
    fprintf(aswingIn,'\n');
    fprintf(aswingIn,'    t       EIcc     EInn     GJ  EA   EIcn   EIcs  EIsn  Cea  Nea  Cta  Nta  mgcc  Ccg  Ncg\n');
    for i=1:length(optim.boom.omlSectionsX_m{index})
        fprintf(aswingIn,'\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\t%3.4f\n', ...
            optim.boom.omlSectionsX_m{index}(i)/ optim.boom.omlSectionsX_m{index}(end), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.EIcc_Nm2{index},  optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.EInn_Nm2{index},  optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.GJ_Nm2{index},    optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.EA_N{index},      optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.EIcn_Nm2{index},  optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.EIcs_Nm2{index},  optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.EIsn_Nm2{index},  optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Cea_m{index},     optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Nea_m{index},     optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Cta_m{index},     optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Nta_m{index},     optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.mgcc_Nm{index},   optim.boom.omlSectionsX_m{index}(i), 'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Ccg_m{index},     optim.boom.omlSectionsX_m{index}(i),'linear','extrap'), ...
            interp1(optim.boom.structure.sRefY_m{index}, optim.boom.structure.Ncg_m{index},     optim.boom.omlSectionsX_m{index}(i),'linear','extrap'));
    end
end

fprintf(aswingIn,'End\n');

end

